/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLoginProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createLoginChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exchangeIdentityToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConnectionCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/naver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["connectNaverMail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{provider}/oauth/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["beginConnectionOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{provider}/oauth/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeConnectionOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connectionId}/monitoring-consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateConnectionMonitoringConsent"];
        trace?: never;
    };
    "/connections/{connectionId}/monitoring/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeConnectionMonitoring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listImportRuns"];
        put?: never;
        post: operations["createImportRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import-runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getImportRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import-runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelImportRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApplicationCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApplicationPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/details": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateApplicationDetails"];
        trace?: never;
    };
    "/applications/{applicationId}/memo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["updateApplicationMemo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateApplicationStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get: operations["getApplicationSchedule"];
        put: operations["replaceApplicationSchedule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchApplicationSchedule"];
        trace?: never;
    };
    "/applications/{applicationId}/schedule/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeApplicationSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/review/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeApplicationReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/review/complete-bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeAllApplicationReviews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/activities/{activityId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                activityId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteApplicationActivity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/emails": {
        parameters: {
            query?: {
                before?: components["parameters"]["HistoryBefore"];
                limit?: components["parameters"]["HistoryLimit"];
            };
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get: operations["listApplicationEmails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/activities": {
        parameters: {
            query?: {
                before?: components["parameters"]["HistoryBefore"];
                limit?: components["parameters"]["HistoryLimit"];
            };
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get: operations["listApplicationActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/changes": {
        parameters: {
            query?: {
                before?: components["parameters"]["HistoryBefore"];
                limit?: components["parameters"]["HistoryLimit"];
            };
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get: operations["listApplicationChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHomeSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCalendarSchedules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApplicationAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecentActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar-exports/previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCalendarExportPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar-exports/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["CalendarExportId"];
            };
            cookie?: never;
        };
        get: operations["getCalendarExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar-exports/{exportId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["CalendarExportId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmCalendarExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        LoginProvider: "google" | "kakao";
        LoginProviderResponse: {
            provider: components["schemas"]["LoginProvider"];
            configured: boolean;
        };
        CreateLoginChallengeRequest: {
            provider: components["schemas"]["LoginProvider"];
        };
        ExchangeIdentityTokenRequest: {
            provider: components["schemas"]["LoginProvider"];
            idToken: string;
            challengeToken: string;
            nonce: string;
        };
        LoginChallenge: {
            challengeToken: string;
            nonce: string;
            /** Format: date-time */
            expiresAt: string;
        };
        AuthUser: {
            /** Format: uuid */
            id: string;
            displayName: string | null;
            primaryEmail: string | null;
        };
        AuthSession: {
            accessToken: string;
            /** @constant */
            tokenType: "Bearer";
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["AuthUser"];
        };
        /** @enum {string} */
        ConnectionProvider: "gmail" | "outlook" | "naver" | "google_calendar";
        ConnectionCapability: {
            provider: components["schemas"]["ConnectionProvider"];
            /** @enum {string} */
            capability: "mail" | "calendar";
            /** @enum {string} */
            connectionMode: "oauth2" | "app_password";
            available: boolean;
            supportsHistoricalImport: boolean;
            supportsOngoingSync: boolean;
            notes: string[];
        };
        ExternalConnection: {
            /** Format: uuid */
            id: string;
            provider: components["schemas"]["ConnectionProvider"];
            /** @enum {string} */
            capability: "mail" | "calendar";
            /** Format: email */
            accountEmail: string;
            /** @enum {string} */
            status: "connected" | "reauthorization_required" | "error" | "revoked";
            ongoingSyncConsent: boolean;
            /** Format: date-time */
            lastSyncedAt: string | null;
            /** Format: date-time */
            nextSyncAfter: string | null;
            lastErrorCode: string | null;
            monitoringPaused: boolean;
            /** Format: date-time */
            tokenExpiresAt: string | null;
            grantedScopes: string[];
            /** Format: int64 */
            version: number;
        };
        ConnectNaverRequest: {
            /** Format: email */
            accountEmail: string;
            appPassword: string;
            ongoingSyncConsent: boolean;
        };
        BeginOAuthConnectionRequest: {
            redirectUri: string;
        };
        BeginOAuthConnectionResponse: {
            provider: components["schemas"]["ConnectionProvider"];
            /** Format: uri */
            authorizationUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        CompleteOAuthConnectionRequest: {
            state: string;
            code: string;
            ongoingSyncConsent: boolean;
        };
        UpdateMonitoringConsentRequest: {
            /** Format: int64 */
            expectedVersion: number;
            enabled: boolean;
        };
        ResumeMonitoringRequest: {
            /** Format: int64 */
            expectedVersion: number;
        };
        CreateImportRunRequest: {
            /** Format: uuid */
            mutationId: string;
            /** Format: uuid */
            connectionId: string;
            /** Format: date */
            dateFrom?: string;
            /** Format: date */
            dateTo?: string;
        };
        ImportRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            connectionId: string;
            /** Format: int64 */
            connectionVersion: number;
            provider: components["schemas"]["ConnectionProvider"];
            /** @enum {string} */
            requestedBy: "user" | "monitor";
            /** Format: date */
            dateFrom: string;
            /** Format: date */
            dateTo: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed" | "cancelled";
            scannedCount: number;
            finalizedCount: number;
            ignoredCount: number;
            duplicateCount: number;
            errorCode: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            completedAt: string | null;
            /** Format: date-time */
            purgeAfter: string;
            /** Format: date-time */
            createdAt: string;
        };
        ImportRunPage: {
            items: components["schemas"]["ImportRun"][];
            page: number;
            size: number;
            hasNext: boolean;
        };
        /** @enum {string} */
        ApplicationStatus: "applied" | "screening" | "test" | "interview" | "offer" | "offered" | "rejected";
        /**
         * @default all
         * @enum {string}
         */
        ApplicationFilter: "all" | "review" | "application" | "test" | "interview" | "offer" | "offered" | "rejected" | "schedulable";
        /** @enum {string} */
        ApplicationSourceType: "manual" | "gmail" | "outlook" | "naver" | "other";
        /** @enum {string} */
        ScheduleType: "application" | "test" | "interview" | "followup" | "other";
        /** @enum {string} */
        ActivityType: "email" | "note" | "status" | "task";
        MutationRequest: {
            /** Format: uuid */
            mutationId: string;
            /** Format: int64 */
            expectedVersion: number;
        };
        CreateApplicationRequest: {
            /** Format: uuid */
            mutationId: string;
            company: string;
            position: string;
            /** @enum {string} */
            status: "applied" | "screening" | "test" | "interview" | "offer";
        };
        UpdateApplicationDetailsRequest: {
            /** Format: uuid */
            mutationId: string;
            /** Format: int64 */
            expectedVersion: number;
            company: string;
            position: string;
            location: string | null;
            employmentType: string | null;
            /** Format: date */
            appliedAt: string;
        };
        UpdateMemoRequest: {
            /** Format: uuid */
            mutationId: string;
            /** Format: int64 */
            expectedVersion: number;
            memo: string;
        };
        UpdateStatusRequest: {
            /** Format: uuid */
            mutationId: string;
            /** Format: int64 */
            expectedVersion: number;
            status: components["schemas"]["ApplicationStatus"];
        };
        PatchScheduleRequest: {
            /** Format: uuid */
            mutationId: string;
            /** Format: int64 */
            expectedVersion: number;
            /** Format: date */
            nextActionAt?: string;
            nextActionTitle?: string;
        } | unknown | unknown;
        ReplaceScheduleRequest: {
            /** Format: uuid */
            mutationId: string;
            /** Format: int64 */
            expectedVersion: number;
            /** Format: int64 */
            expectedScheduleVersion?: number;
            scheduleType: components["schemas"]["ScheduleType"];
            action: string;
            /** Format: date-time */
            scheduledAt: string;
            /** Format: date-time */
            endsAt: string | null;
            timezone: string;
            location: string;
            description: string;
        };
        ApplicationListItem: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            version: number;
            company: string;
            position: string;
            /** Format: date */
            appliedAt: string;
            status: components["schemas"]["ApplicationStatus"];
            needsReview: boolean;
            source: string;
        };
        Application: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            version: number;
            company: string;
            position: string;
            location: string;
            employmentType: string;
            /** Format: date */
            appliedAt: string;
            status: components["schemas"]["ApplicationStatus"];
            needsReview: boolean;
            source: string;
            sourceType: components["schemas"]["ApplicationSourceType"];
            schedule: components["schemas"]["ApplicationScheduleSummary"] | null;
            memo: string;
        };
        ApplicationScheduleSummary: {
            nextActionTitle: string;
            /** Format: date */
            nextActionAt: string;
        };
        ApplicationPage: {
            items: components["schemas"]["ApplicationListItem"][];
            page: number;
            limit: number;
            hasNext: boolean;
            /** Format: int64 */
            filteredCount: number;
            /** Format: int64 */
            totalCount: number;
            /** Format: int64 */
            needsReviewCount: number;
            /** Format: int64 */
            reviewRevision: number;
        };
        ApplicationCounts: {
            /** Format: int64 */
            totalCount: number;
        };
        CompleteBulkReviewRequest: {
            /** Format: uuid */
            mutationId: string;
            /** Format: int64 */
            expectedReviewRevision: number;
        };
        CompleteBulkReviewResponse: {
            completedCount: number;
            /** Format: int64 */
            needsReviewCount: number;
            /** Format: int64 */
            reviewRevision: number;
        };
        ApplicationEmail: {
            /** Format: uuid */
            id: string;
            subject: string;
            sender: string;
            /** Format: date-time */
            receivedAt: string;
            summary: string;
        };
        ApplicationActivity: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["ActivityType"];
            title: string;
            description: string;
            /** Format: date-time */
            occurredAt: string;
        };
        ApplicationChange: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            /** Format: date-time */
            occurredAt: string;
        };
        ApplicationSchedule: components["schemas"]["AllDayApplicationSchedule"] | components["schemas"]["TimedApplicationSchedule"];
        AllDayApplicationSchedule: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            applicationId: string;
            /** Format: int64 */
            applicationVersion: number;
            /** Format: int64 */
            version: number;
            scheduleType: components["schemas"]["ScheduleType"];
            action: string;
            /** @constant */
            allDay: true;
            /** Format: date */
            date: string;
            scheduledAt: null;
            endsAt: null;
            timezone: null;
            location: string;
            description: string;
            completed: boolean;
            /** Format: date-time */
            completedAt: string | null;
        };
        TimedApplicationSchedule: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            applicationId: string;
            /** Format: int64 */
            applicationVersion: number;
            /** Format: int64 */
            version: number;
            scheduleType: components["schemas"]["ScheduleType"];
            action: string;
            /** @constant */
            allDay: false;
            date: null;
            /** Format: date-time */
            scheduledAt: string;
            /** Format: date-time */
            endsAt: string | null;
            timezone: string;
            location: string;
            description: string;
            completed: boolean;
            /** Format: date-time */
            completedAt: string | null;
        };
        EmailHistoryPage: {
            items: components["schemas"]["ApplicationEmail"][];
            /** Format: int64 */
            nextCursor: number | null;
            /** Format: int64 */
            totalCount: number;
        };
        ActivityHistoryPage: {
            items: components["schemas"]["ApplicationActivity"][];
            /** Format: int64 */
            nextCursor: number | null;
        };
        ChangeHistoryPage: {
            items: components["schemas"]["ApplicationChange"][];
            /** Format: int64 */
            nextCursor: number | null;
            /** Format: int64 */
            totalCount: number;
        };
        HomeSummary: {
            /** Format: date */
            date: string;
            briefing: components["schemas"]["HomeBriefing"];
            priorityItems: components["schemas"]["HomePriorityItem"][];
            upcomingSchedules: components["schemas"]["HomeUpcomingSchedule"][];
            activeApplications: components["schemas"]["HomeActiveApplication"][];
        };
        HomeBriefing: {
            /** @enum {string} */
            reason: "needsReview" | "openTask" | "upcomingSchedule" | "idle";
            /** Format: int64 */
            count: number;
        };
        HomePriorityItem: {
            /** Format: uuid */
            applicationId: string;
            /** Format: int64 */
            applicationVersion: number;
            company: string;
            position: string;
            /** @enum {string} */
            reason: "needsReview" | "overdue" | "today";
            scheduleType: components["schemas"]["ScheduleType"] | null;
            /** Format: date */
            nextActionAt: string | null;
            canComplete: boolean;
        };
        HomeUpcomingSchedule: {
            /** Format: uuid */
            applicationId: string;
            company: string;
            position: string;
            scheduleType: components["schemas"]["ScheduleType"];
            /** Format: date */
            date: string;
        };
        HomeActiveApplication: {
            /** Format: uuid */
            applicationId: string;
            company: string;
            position: string;
            status: components["schemas"]["ApplicationStatus"];
            needsReview: boolean;
            /** Format: date */
            nextActionAt: string | null;
            latestActivityTitle: string;
        };
        CalendarSchedulePage: {
            items: components["schemas"]["CalendarScheduleItem"][];
        };
        CalendarScheduleItem: {
            /** Format: uuid */
            applicationId: string;
            company: string;
            position: string;
            status: components["schemas"]["ApplicationStatus"];
            needsReview: boolean;
            title: string;
            /** Format: date */
            date: string;
        };
        ApplicationAnalytics: {
            /** Format: date */
            from: string | null;
            /** Format: date */
            to: string;
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            screeningPassed: number;
            /** Format: int64 */
            reachedInterview: number;
            /** Format: int64 */
            offered: number;
            monthlyFlow: components["schemas"]["MonthlyFlow"][];
            /** @description Sparse counts keyed by the canonical application source type. */
            sourceCounts: {
                /** Format: int64 */
                gmail?: number;
                /** Format: int64 */
                naver?: number;
                /** Format: int64 */
                outlook?: number;
                /** Format: int64 */
                manual?: number;
                /** Format: int64 */
                other?: number;
            };
        };
        MonthlyFlow: {
            month: string;
            /** Format: int64 */
            count: number;
        };
        RecentActivity: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            applicationId: string;
            company: string;
            position: string;
            type: components["schemas"]["ActivityType"];
            title: string;
            description: string;
            /** Format: date-time */
            occurredAt: string;
        };
        CreateCalendarPreviewRequest: {
            /** Format: uuid */
            scheduleId: string;
            /** Format: uuid */
            connectionId: string;
            /** Format: uuid */
            idempotencyKey: string;
            /** Format: int64 */
            expectedScheduleVersion: number;
        };
        ConfirmCalendarExportRequest: {
            previewHash: string;
        };
        CalendarExport: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scheduleId: string;
            /** Format: uuid */
            connectionId: string;
            /** Format: int64 */
            scheduleVersion: number;
            previewHash: string;
            title: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            timezone: string;
            location: string;
            description: string;
            /** @enum {string} */
            status: "previewed" | "confirming" | "confirmed" | "failed";
            providerEventId: string | null;
            errorCode: string | null;
            /** Format: date-time */
            confirmedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ProblemDetail: {
            /**
             * Format: uri-reference
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail: string;
            /** Format: uri-reference */
            instance?: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Updated application. */
        ApplicationResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Application"];
            };
        };
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Authentication is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Owned resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Mutation id or optimistic version conflict. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Request rate limit exceeded. */
        TooManyRequests: {
            headers: {
                "Retry-After": number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description A required provider or service is unavailable. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The external provider requires another action. */
        FailedDependency: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        OAuthConnectionProvider: "gmail" | "outlook" | "google_calendar";
        ConnectionId: string;
        ImportRunId: string;
        ApplicationId: string;
        CalendarExportId: string;
        ApplicationQuery: string;
        ApplicationStatusFilter: components["schemas"]["ApplicationFilter"];
        HistoryBefore: number;
        HistoryLimit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listLoginProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Login provider configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginProviderResponse"][];
                };
            };
        };
    };
    createLoginChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLoginChallengeRequest"];
            };
        };
        responses: {
            /** @description One-time login challenge. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginChallenge"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    exchangeIdentityToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeIdentityTokenRequest"];
            };
        };
        responses: {
            /** @description Server-issued opaque session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked or already absent. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listConnectionCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider capabilities and current availability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionCapability"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listConnections: {
        parameters: {
            query?: {
                capability?: "mail" | "calendar";
                includeRevoked?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connections owned by the current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalConnection"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    connectNaverMail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectNaverRequest"];
            };
        };
        responses: {
            /** @description Validated and encrypted Naver mail connection. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalConnection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    beginConnectionOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["parameters"]["OAuthConnectionProvider"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeginOAuthConnectionRequest"];
            };
        };
        responses: {
            /** @description Provider authorization URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeginOAuthConnectionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    completeConnectionOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["parameters"]["OAuthConnectionProvider"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteOAuthConnectionRequest"];
            };
        };
        responses: {
            /** @description Connected provider account. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalConnection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            424: components["responses"]["FailedDependency"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateConnectionMonitoringConsent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectionId: components["parameters"]["ConnectionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMonitoringConsentRequest"];
            };
        };
        responses: {
            /** @description Updated connection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalConnection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    resumeConnectionMonitoring: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectionId: components["parameters"]["ConnectionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeMonitoringRequest"];
            };
        };
        responses: {
            /** @description Resumed connection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalConnection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    revokeConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectionId: components["parameters"]["ConnectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listImportRuns: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import runs ordered newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRunPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createImportRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateImportRunRequest"];
            };
        };
        responses: {
            /** @description Queued or replayed import run. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getImportRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["ImportRunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import run state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelImportRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["ImportRunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled import run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Created application. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getApplicationCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unfiltered application count. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationCounts"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listApplicationPage: {
        parameters: {
            query?: {
                q?: components["parameters"]["ApplicationQuery"];
                status?: components["parameters"]["ApplicationStatusFilter"];
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A bounded application page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Core application detail; histories are fetched from their bounded endpoints. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateApplicationDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationDetailsRequest"];
            };
        };
        responses: {
            200: components["responses"]["ApplicationResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateApplicationMemo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemoRequest"];
            };
        };
        responses: {
            200: components["responses"]["ApplicationResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateApplicationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStatusRequest"];
            };
        };
        responses: {
            200: components["responses"]["ApplicationResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getApplicationSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full all-day or timed schedule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationSchedule"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceApplicationSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceScheduleRequest"];
            };
        };
        responses: {
            /** @description Replaced schedule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationSchedule"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    patchApplicationSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchScheduleRequest"];
            };
        };
        responses: {
            200: components["responses"]["ApplicationResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    completeApplicationSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutationRequest"];
            };
        };
        responses: {
            200: components["responses"]["ApplicationResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    completeApplicationReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutationRequest"];
            };
        };
        responses: {
            200: components["responses"]["ApplicationResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    completeAllApplicationReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteBulkReviewRequest"];
            };
        };
        responses: {
            /** @description Review completion result for the current review revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteBulkReviewResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteApplicationActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
                activityId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutationRequest"];
            };
        };
        responses: {
            200: components["responses"]["ApplicationResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listApplicationEmails: {
        parameters: {
            query?: {
                before?: components["parameters"]["HistoryBefore"];
                limit?: components["parameters"]["HistoryLimit"];
            };
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email history page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailHistoryPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listApplicationActivities: {
        parameters: {
            query?: {
                before?: components["parameters"]["HistoryBefore"];
                limit?: components["parameters"]["HistoryLimit"];
            };
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity history page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityHistoryPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listApplicationChanges: {
        parameters: {
            query?: {
                before?: components["parameters"]["HistoryBefore"];
                limit?: components["parameters"]["HistoryLimit"];
            };
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Change history page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeHistoryPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getHomeSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded data needed by the home route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listCalendarSchedules: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Incomplete schedules in an inclusive range of at most 62 days. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarSchedulePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getApplicationAnalytics: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application analytics for an optional inclusive date range. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationAnalytics"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listRecentActivities: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                type?: components["schemas"]["ActivityType"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent activities in an inclusive range of at most 31 days. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentActivity"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createCalendarExportPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCalendarPreviewRequest"];
            };
        };
        responses: {
            /** @description Persisted export preview. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarExport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getCalendarExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["CalendarExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calendar export state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarExport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    confirmCalendarExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["CalendarExportId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmCalendarExportRequest"];
            };
        };
        responses: {
            /** @description Confirmed or replayed calendar export. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarExport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            424: components["responses"]["FailedDependency"];
        };
    };
}
